- hosts: "{{ env }}"
  become: yes
  tasks: 
    - name: remove any previous app services
      shell: | 
         if [ `kubectl get deploy | grep -v NAME | awk '{print $1}' | grep abcapp | wc -l` -gt 0 ]; then  
            kubectl delete deploy `kubectl get deploy | grep -v NAME | awk '{print $1}' | grep abcapp`
         else 
            echo "No app deployments found"
         fi
         if [ `kubectl get svc | grep abcapp-svc  | awk '{print $1}' | wc -l` -gt 0 ]; then
            kubectl delete svc `kubectl get svc | grep abcapp-svc | awk '{print $1}'`
         else
            echo "No app service found"
         fi
    - name: deploy app
      command: kubectl create deploy abcapp --image=mrathna/abcapp:{{ build }}
    - name: increase replicas 
      command: kubectl scale deploy abcapp --replicas=2
    - name: deploy service
      command: kubectl expose deploy abcapp --name myapp-svc --port 8080 --type NodePort

